apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
      app:  nginx
spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx-test
                  imagePullPolicy: Never
                  image: nginx-test
                  ports:
                      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
      app: nginx
    type: NodePort
    ports:
      - port: 80
      NodePort: 31364
      targetPort: 80
      protocol: TCP
      name: http