apiVersion: nginx/v1
kind: Deployment
metadata:
    name: activity_3-deployment
    labels:
      app:  nginx
spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx-test
                  imagePullPolicy: Never
                  image: local/nginx-test
                  ports:
                      - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
    name: activity_3-service
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
        - port: 80
          targetPort: 8080