name: CI/CD task

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Image building and deploy to minikube
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Checking cluster
      run:  kubectl get pods -A
    - name: Build image
      run:  |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./activity_3/Dockerfile -t nginx-test ./activity_3
        echo -n "Verifying images:"
        docker images
    - name: Deploy cluster using minikube
      run: kubectl apply -f ./activity_3/deploy.yaml
        kubectl expose deployment nginx-test --name=nginx-test --type=LoadBalancer --target-port=80
    - name: Test service
      run:  |
        minikube service list
        minikube service nginx-service --url
        echo -n "------------------opening the service------------------"
        curl $(minikube service nginx-service --url)/version